// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KAE.CMTools.Generator.templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using KAE.CMTools.Core;
    using KAE.CMTools.Core.DataType;
    using KAE.CMTools.Generator.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class InstanceSchema : InstanceSchemaBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

  // Copyright (c) Knowledge & Experience. All rights reserved.
  // Licensed under the MIT license. See LICENSE file in the project root for full license information.

            
            #line default
            #line hidden
            this.Write("\r\n# This schema is generated by DomainSchemaGenerator\r\n$schema: \"https://json-sch" +
                    "ema.org/draft/2020-12/schema\"\r\n$title: \"");
            
            #line 17 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.domain.Name));
            
            #line default
            #line hidden
            this.Write(@"""
type: object
required: [fos]
properties:
  fos:
    type: object
    required: [fosId, domain, date, instances]
    properties:
      fosId:
        type: string
        format: uuid
      domain:
        type: string
      date:
        type: string
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      instances:
        type: array
        items:
          type: object
          required: [instance, properties]
          properties:
            instance:
              type: string
              format: uuid
            properties:
              oneOf:
");
            
            #line 44 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

    foreach (var keyLett in this.domain.ConceptualClasses.Keys)
    {

            
            #line default
            #line hidden
            this.Write("                - $ref: \"#/$defs/");
            
            #line 48 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyLett));
            
            #line default
            #line hidden
            this.Write("\"\r\n");
            
            #line 49 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n$defs:\r\n");
            
            #line 54 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

    foreach (var keyLett in this.domain.ConceptualClasses.Keys)
    {
        var cclass = this.domain.ConceptualClasses[keyLett];
        string name = cclass.Name;
        string number = cclass.Number;

        string propertyNameList = this.GetPropertyNameList(cclass);

            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 63 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyLett));
            
            #line default
            #line hidden
            this.Write(":\r\n    type: object\r\n    required: [cclass, ");
            
            #line 65 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyNameList));
            
            #line default
            #line hidden
            this.Write("]\r\n    properties:\r\n      cclass:\r\n        const: ");
            
            #line 68 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(keyLett));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 69 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

        foreach (var propName in cclass.Properties.Keys)
        {
            var property = cclass.Properties[propName];
            if (!property.IsMethematical)
            {
                bool isDenote = property.IsDenote;
                string grammar = property.Grammar;
                var dataType = property.BaseDataType;
                string dataTypeName = dataType.Name;
                string format = "";
                if (dataType is PrimitiveDataType)
                {
                    (dataTypeName, format) = YamlDataTypeTranslator.ToYamlTypeName(((PrimitiveDataType)dataType).Kind);
                    if (property.IsNullable || property.IsParticipantProperty())
                    {
                        dataTypeName = $"[{dataTypeName}, \"null\"]";
                    }
                }
                string dataTypeComment = "";
                if (property.DataType.Name == DataType.DataTypeKind.UNIQUE_ID.ToString()
                    || property.DataType.Name == DataType.DataTypeKind.OTHER.ToString()
                            || property.DataType.Name == DataType.DataTypeKind.REFERENCE.ToString()
                            || property.DataType.Name==DataType.DataTypeKind.UNKNOWN.ToString())
                {
                    dataTypeComment = $"# {property.DataType.Name}";
                }

            
            #line default
            #line hidden
            this.Write("      ");
            
            #line 97 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propName));
            
            #line default
            #line hidden
            this.Write(":\r\n        type: ");
            
            #line 98 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataTypeName));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 99 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

                if (!string.IsNullOrEmpty(format))
                {

            
            #line default
            #line hidden
            this.Write("        format: ");
            
            #line 103 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(format));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 104 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

                }
                if (!string.IsNullOrEmpty(dataTypeComment))
                {

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 109 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dataTypeComment));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 110 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

                }

            
            #line default
            #line hidden
            
            #line 113 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

                if (!string.IsNullOrEmpty(grammar))
                {

            
            #line default
            #line hidden
            this.Write("        pattern: \'");
            
            #line 117 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(grammar));
            
            #line default
            #line hidden
            this.Write("\'\r\n");
            
            #line 118 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

                }
            }
        }

            
            #line default
            #line hidden
            this.Write("    additionalProperties: false\r\n");
            
            #line 124 "C:\Users\kae-m\source\repos\CMToolCore\KAE.CMTools.Generator\templates\InstanceSchema.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class InstanceSchemaBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
